export default {
    AlbumPicker: require('./AlbumPicker').default,
    AlbumListItem: require('./AlbumListItem').default,
    ArtistListItem: require('./ArtistListItem').default,
    AudioControls: require('./AudioControls').default,
    AudioPlayer: require('./AudioPlayer').default,
    CoverArt: require('./CoverArt').default,
    Href: require('@uirouter/react').UISref,
    LinkTile: require('./LinkTile').default,
    LoginForm: require('./LoginForm').default,
    NavBar: require('./NavBar').default,
    RangeInput: require('./RangeInput').default,
    ReactHowlerPlayer: require('./ReactHowlerPlayer').default,
    SongDuration: require('./SongDuration').default,
    SongPickerItem: require('./SongPickerItem').default,
    SongPicker: require('./SongPicker').default,
}
